In [2]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)
type(arr)
twodarr=np.array([[1,2,3,4],[5,6,7,8]])
print(twodarr)

[1 2 3 4 5 6]
[[1 2 3 4]
 [5 6 7 8]]


In [3]:

# creating a sample array (dummy data)
arr = np.array([10, 20, 30, 40, 50])

# print original data
print("Array values:", arr)

# check total elements
print("Array size:", arr.size)

# check array shape
print("Array shape:", arr.shape)

# sum of all values
total = np.sum(arr)
print("Sum:", total)

# average using average()
avg = np.average(arr)
print("Average using np.average:", avg)

# mean using mean()
m = np.mean(arr)
print("Mean using np.mean:", m)

# max and min values
print("Maximum value:", np.max(arr))
print("Minimum value:", np.min(arr))

# standard deviation
print("Standard deviation:", np.std(arr))

Array values: [10 20 30 40 50]
Array size: 5
Array shape: (5,)
Sum: 150
Average using np.average: 30.0
Mean using np.mean: 30.0
Maximum value: 50
Minimum value: 10
Standard deviation: 14.142135623730951
